---
title: "Schedule"
description: |
 Schedule and course materials for Statistical Computing (JHSPH Biostatistics 140.776 Fall 2021).
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Schedule and course materials

For Rmd files, go to the [course GitHub repository](https://github.com/stephaniehicks/jhustatcomputing2021) and navigate the directories, or best of all to clone the repo and navigate within RStudio.

::: l-body-outset
| Week   | Dates           | Topics                             | Podcast | Projects | 
|--------- | ----------- | ----------------------------------- | --------------- | --------------- |
| **Module 1** |    | **Statistical and computational tools for scientific and reproducible research** |  |
| | | | | |
| Week 1      | Aug 31  | `r emojifont::emoji('wave')` Course introduction [[html](posts/welcome/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/welcome/welcome.Rmd)] | |  `r emojifont::emoji('palm_tree')` Project 0 [[html](projects/2021-08-31-project-0/index.html)] |
| | | `r emojifont::emoji('woman_technologist')` Introduction to R and RStudio [[html](posts/2021-08-31-introduction-to-r-and-rstudio/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-08-31-introduction-to-r-and-rstudio/introduction-to-r-and-rstudio.Rmd)] | | |
| | | `r emojifont::emoji('octopus')` Introduction to git/GitHub [[html](posts/2021-08-31-introduction-to-gitgithub/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-08-31-introduction-to-gitgithub/introduction-to-gitgithub.Rmd)] |  | |
| | | | | |
| | Sept 2 | `r emojifont::emoji('microscope')` Reproducible Research [[html](posts/2021-09-02-reproducible-research/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-09-02-reproducible-research/reproducible-research.Rmd)] |  | |
| | | `r emojifont::emoji('eyeglasses')` Literate programming [[html](posts/2021-09-02-literate-programming/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-09-02-literate-programming/literate-programming.Rmd)] |  | |
| | | `r emojifont::emoji('cool')` Reference management [[html](posts/2021-09-02-reference-management/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-09-02-reference-management/reference-management.Rmd)] |  | |
| | | | | |
| Week 2      | Sept 7       | `r emojifont::emoji('construction')` Getting and cleaning data [[html](posts/2021-09-07-reading-and-writing-data/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-09-07-reading-and-writing-data/reading-and-writing-data.Rmd)] | | `r emojifont::emoji('palm_tree')` Project 1 [[html](projects/2021-09-07-project-1/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_projects/2021-09-07-project-1/project-1.Rmd)] |
| | | `r emojifont::emoji('scissors')` Managing data frames with Tidyverse [[html](posts/2021-09-07-managing-data-frames-with-tidyverse/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-09-07-managing-data-frames-with-tidyverse/managing-data-frames-with-tidyverse.Rmd)] |  | |
| | | | | |
| | Sept 9 | `r emojifont::emoji('heart_eyes_cat')` Tidy data and the Tidyverse [[html](posts/2021-09-07-tidy-data-and-the-tidyverse/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-09-07-tidy-data-and-the-tidyverse/tidy-data-and-the-tidyverse.Rmd)] | | `r emojifont::emoji('fallen_leaf')`  Project 0 due |
| | | `r emojifont::emoji('handshake')` Joining data in R: Basics [[html](posts/2021-09-07-joining-data-in-r/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-09-07-joining-data-in-r/joining-data-in-r.Rmd)] |  | |
| | | `r emojifont::emoji('bar_chart')` Plotting systems in R  [[html](posts/2021-09-09-plotting-systems/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-09-09-plotting-systems/plotting-systems.Rmd)] |  | |
| | | | | |
|   Week 3 | Sept 14  | `r emojifont::emoji('bar_chart')` The ggplot2 plotting system: qplot() [[html](posts/2021-09-14-ggplot2-plotting-system-part-1/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-09-14-ggplot2-plotting-system-part-1/ggplot2-plotting-system-part-1.Rmd)] | `r emojifont::emoji('headphones')` Data viz  | |
| | | `r emojifont::emoji('bar_chart')` The ggplot2 plotting system: ggplot() [[html](posts/2021-09-14-ggplot2-plotting-system-part-2/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-09-14-ggplot2-plotting-system-part-2/ggplot2-plotting-system-part-2.Rmd)] |  | |
| | | |  | |
| **Module 2** |    | **Data analysis in R** |  | |
| | | | | |
|      | Sept 16      | `r emojifont::emoji('nut_and_bolt')` R Nuts and Bolts [[html](posts/2021-09-16-r-nuts-and-bolts/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-09-16-r-nuts-and-bolts/r-nuts-and-bolts.Rmd)] | | `r emojifont::emoji('palm_tree')` Project 2 [[html](projects/2021-09-14-project-2/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_projects/2021-09-14-project-2/project-2.Rmd)] |
| | | `r emojifont::emoji('nut_and_bolt')` Control structures in R [[html](posts/2021-09-16-control-structures/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-09-16-control-structures/control-structures.Rmd)]  | | | 
| |  Sept 17 | | | `r emojifont::emoji('fallen_leaf')`  Project 1 due |
| | | | | |
| Week 4  | Sept 21 | `r emojifont::emoji('nut_and_bolt')` Functions in R [[html](posts/2021-09-21-functions/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-09-21-functions/functions.Rmd)] |  | |
| |  | `r emojifont::emoji('nut_and_bolt')` Loop functions [[html](posts/2021-09-21-loop-functions/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-09-21-loop-functions/loop-functions.Rmd)]  | | |
| | | | | |
| | Sept 23      | `r emojifont::emoji('bug')` Debugging code in R [[html](posts/2021-09-23-debugging-r-code/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-09-23-debugging-r-code/debugging-r-code.Rmd)]  | | | 
| | | `r emojifont::emoji('bug')` Error handling code in R [[html](posts/2021-09-23-error-handling-and-generation/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-09-23-error-handling-and-generation/error-handling-and-generation.Rmd)]  | | |
| | | `r emojifont::emoji('bug')` Profiling R code [[html](posts/2021-09-23-profiling-r-code/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-09-23-profiling-r-code/profiling-r-code.Rmd)] | | |
| | |  | | |
| Week 5 | Sept 28      | `r emojifont::emoji('package')` R package software development [[html](posts/2021-09-28-building-r-packages/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-09-28-building-r-packages/building-r-packages.Rmd)] | `r emojifont::emoji('headphones')` Data analysis | |
| | |  | | |
| | Sept 30      | `r emojifont::emoji('black_circle')` Object Oriented Programming [[html](posts/2021-09-30-object-oriented-programming/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-09-3--object-oriented-programming/object-oriented-programming.Rmd)]  | | | 
| | Oct 1 | | | `r emojifont::emoji('fallen_leaf')`  Project 2 due |
| | | | | |
| Week 6      | Oct 5   | `r emojifont::emoji('calendar')` Working with dates and times [[html](posts/2021-10-05-working-with-dates-and-times/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-10-05-working-with-dates-and-times/working-with-dates-and-times.Rmd)] | | `r emojifont::emoji('palm_tree')` Project 3 [[html](projects/2021-10-05-project-3/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_projects/2021-10-05-project-3/project-3.Rmd)]  |
| | | | | |
| | Oct 7 | `r emojifont::emoji('sparkles')` Regular expressions [[html](posts/2021-10-07-regular-expressions/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-10-07-regular-expressions/regular-expressions.Rmd)] | | |
| | | | | |
| Week 7      | Oct 12        | `r emojifont::emoji('volcano')` SQL basics [[html](posts/2021-10-12-sql-basics/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-10-12-sql-basics/sql-basics.Rmd)] | | |
| | | `r emojifont::emoji('volcano')` Strategies for dealing with large data [[html](posts/2021-10-12-dealing-with-large-data/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-10-12-dealing-with-large-data/dealing-with-large-data.Rmd)]  | | |
| | | `r emojifont::emoji('volcano')` Parallel computation [link to 2020 [html](https://rdpeng.github.io/Biostat776/lecture-parallel-computation.html)] (material not formally covered in 2021 though) | | |
| | | | | |
| | Oct 14 | `r emojifont::emoji('snake')` Leveraging Python within R [[html](posts/2021-10-14-python-for-r-users/index.html)] [[Rmd](https://github.com/stephaniehicks/jhustatcomputing2021/blob/main/_posts/2021-10-14-python-for-r-users/python-for-r-users.Rmd)] | `r emojifont::emoji('headphones')` R package dev | |
| | | | | |
| **Module 3** |    | **Machine Learning Essentials** | |
| | | | | |
| Week 8      | Oct 19       | Machine learning essentials | |
| | | | | |
| | Oct 21 |   Machine learning essentials  | | |
| | | | | |
| |  Oct 22 | | | `r emojifont::emoji('fallen_leaf')`  Project 3 due |
:::

