---
title: "Syllabus"
description: |
 Syllabus for Statistical Computing (JHSPH Biostatistics 140.776 Fall 2021).
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Learning Objectives:

Upon successfully completing this course, students will be able to:

- Install and configure software necessary for a statistical programming environment and with version control
- Discuss generic programming language concepts as they are implemented in a high-level statistical language
- Write and debug code in base R and the tidyverse (and integrate code from Python modules)
- Build basic data visualizations using R and the tidyverse
- Build and organize a software package with documentation for publishing on the internet
- Discuss and implement basic statistical computing algorithms for optimization, linear regression, and Monte Carlo

## Course Information

- Location: Synchronous Online for Fall 2021
- Time: Tuesdays and Thursdays from 1:30-2:50pm
- Assignments: Three projects

## Important Links

- Course website: https://stephaniehicks.com/jhustatcomputing2021
- GitHub repository with all course material: https://github.com/stephaniehicks/jhustatcomputing2021

## Tentative outline of topics

Here is a tentative outline of topics by week for the Fall 2021 course: 

::: l-page
| Week   | Dates           | Description                                        |
|--------|-----------------|-----------------------------------|
| Week 1      | Aug 30-Sept 3   | Introduction to R, RStudio, Github, Reproducible Research, Literate programming, and Tidyverse |
| Week 2      | Sept 6-10       | Data Visualizations in the Tidyverse (colors) |
| Week 3      | Sept 13-17      | Writing and debugging code in base R, Tidyverse, and Python (control structures, functions, regex, etc) |
| Week 4      | Sept 20-24      | R package software development (build, document, test, debug); building personal or project websites |
| Week 5      | Sept 27-Oct 1   | Dealing with large data; parallel computing |
| Week 6      | Oct 4-8         | Basic statistical computing algorithms for linear regression, optimization, EM algorithm, and Monte Carlo |
| Week 7      | Oct 11-15       | Machine learning essentials |
| Week 8      | Oct 18-22       | Bootstrap, smoothing splines,           |
:::

