---
title: "Reference management"
description: |
  Add a short description here.
author:
  - name: Stephanie Hicks
    url: https://stephaniehicks.com/
    affiliation: Department of Biostatistics, Johns Hopkins
    affiliation_url: https://www.jhsph.edu
date: 09-02-2021
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
categories:
  - module 1
  - week 1
  - R Markdown 
  - programming
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<!-- Add interesting quote -->


# Pre-lecture materials

### Read ahead

:::resources

**Before class, you can prepare by reading the following materials:**

1. 

:::


### Acknowledgements

Material for this lecture was borrowed and adopted from

- https://andreashandel.github.io/MADAcourse/
- https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html
- 

# Learning objectives

:::keyideas

**At the end of this lesson you will:**

- Know how to manage references (i.e. citations) using R and R Markdown.
- 
- 

:::


# Reference management with R Markdown

For almost any data analysis, especially if it is meant for publication in the academic literature, you will have to cite other people's work and include the references (bibliographies or citations) in your work. In this class, you are likely to need to include references and cite other people's work like in a regular research paper.

I assume you are familiar with how citing references works, and hopefully, you are already using a reference manager. If not, let me know in the discussion boards. 

To have something that plays well with R Markdown, you need file format that stores all the references. Click here to learn more about all the possible file formats available to you to use within a R Markdown file: 

- https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html

As you can see, there are ton of file formats including `.medline` (MEDLINE), `.bibtex` (BibTeX), `.ris` (RIS), `.enl` (EndNote)


The work horse behind this is (pandoc)[https://pandoc.org]. I won't go into much detail here, but generally pandoc is useful if you need to convert files from one markup format into another. And in this case, it can help us automatically generate citations and a bibliography in a number of styles. 

In order to use references within a R Markdown file, you will need to specify the name and a location of a bibliography file using the bibliography metadata field in a YAML metadata section. For example:

```
---
title: "Sample Document"
output: html_document
bibliography: bibliography.bibtex
---
````

Inside your file that contains all your references (e.g. `bibliography.bibtex`), typically each reference gets a key, which is a shorthand that is generated by the reference manager or you can create yourself. 

For instance, I use a format of lower-case first author last name followed by 4 digit year for each reference followed by a keyword (e.g name of a software package). Alternatively, you can omit the keyword. But note that if I cite a paper by the same first author that was published in the same year, then a lower case letter is added to the end. For instance, for a paper that I wrote as 1st author in 2010, my bibtex key might be `hicks2021` or `hicks2021a`. You can decide what scheme to use, just pick one and use it _forever_. 

In your R Markdown document, you can then cite the reference by adding the key, such as `...in the paper by Hicks et al. [@hicks2021]...`. 

When you knit the markdown file, it looks for a reference with the specified tag in your `bibliography.bibtex` file and places all references at the end of your document using the formatting you specified.  

# Post-lecture materials

### Final Questions 

Here are some post-lecture questions to help you think about the material discussed.

:::questions

**Questions:**

1. 

2. 

3.

:::


### Additional Resources 

:::resources 

- 
- 
- 

::: 
