---
title: "Project 1"
description: |
  Information for Project 1
author:
  - name: Stephanie Hicks
    url: https://stephaniehicks.com/
    affiliation: Department of Biostatistics, Johns Hopkins
    affiliation_url: https://www.jhsph.edu
date: 09-07-2021
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
categories:
  - project 1
  - projects
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Background

**Due date: Sept 17 at 11:59pm**

Information coming soon.

#### Tips for increasing the reproducibility of your code 

- You should make sure your code is executed when the document is compiled (so use `eval=FALSE`  sparingly). Most code chunks should be run, especially those that create plots.
- You should have the document create figures as a part of the document compiling, rather than producing the figures in advance with distinct code and then embedding them in the HTML.
- A good best practice is to have your library calls all in the first "setup" chunk of your Rmarkdown file. That helps readers take a quick look and see what they need to run your code and to identify any issues or potential hidden dependencies.
- Your document should knit, in full, with a press of the knit button, with no user input required. This is a really important (and challenging!) part of reproducibility. As a simple check you might try exiting R and then starting a new session and recompiling your document with a clean session to make sure it runs. Another good idea is to move your whole project to a separate sub-folder and trying to run it. The gold standard would be having a friend try to run your document on their computer.
- An absolute path is a path which tells you exactly how to get to a file/folder starting from "root" (usually, it will start with a `"/"` or start with the address of a particular drive; ie, `"C://"`). This is not reproducible because an absolute path, more often than not, is going to be unique to your particular computer and layout. Rather, you should use relative paths. A relative path will start with the current directory, and you index off that. In the case of our homework documents, this means that any scripts/files/dependencies/etc you need should be pushed directly to your repository, and then you load them with a relative path inside your actual homework assignment (relative your working directory). Usually, a relative path will start with "./script.R" or you just specify a file directly; e.g., "script.R" (which the computer interprets as "start from the directory I am in") or might start with telling you to go back a directory or something first ("../"). An important consideration: your R terminal within Rstudio (the little arrow at the bottom; >, that executes raw R commands) will place the "working directory" somewhere (possibly) different from your markdown document. However, if you use the built-in Rmarkdown IDE in RStudio (e.g., pressing the green "run" arrow, or knitting the document) the working directory will be the same directory as the markdown document you are compiling. You might also consider the here package if you are using R to set your paths.
- Not everything needs to be run in real time. A few students (accurately) note that if you have, say, a code block that takes 20 minutes to run, it is perfectly acceptable/understandable to set that block to `eval=FALSE` , save whatever that block produces to say a rds object or a csv that you push to your repo, and at the top of the next block, load it in.
